[options]
; Database configuration
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
db_name = postgres

; Server configuration
http_port = 8069
secure_connection = False
workers = 0

; File storage
data_dir = /var/lib/odoo

; Addons
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons

; Logging
log_level = info
log_handler = :INFO

; Security
admin_passwd = admin

; Email
smtp_server = localhost
smtp_port = 25
smtp_user = 
smtp_password =
